# -*- coding: utf-8 -*-
"""MAS_IAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AydM_7ASxRphKusHe2WyXa00GMnZ2nSQ
"""

# @title Step 0: Setup and Installation
# Install ADK and LiteLLM for multi-model support

!pip install google-adk -q
!pip install litellm -q

print("Installation complete.")

# Commented out IPython magic to ensure Python compatibility.
# Create a project folder
!adk create mas_ias

# Navigate into it (for the next steps)
# %cd mas_ias

# @title Import necessary libraries
import os
import asyncio
from google.adk.agents import ParallelAgent, SequentialAgent, LlmAgent
from google.adk.models.lite_llm import LiteLlm # For multi-model support
from google.adk.sessions import InMemorySessionService
from google.adk.runners import Runner
from google.genai import types # For creating message Content/Parts

import warnings
# Ignore all warnings
warnings.filterwarnings("ignore")

import logging
logging.basicConfig(level=logging.ERROR)

print("Libraries imported.")

# --- Define Model Constants for easier use ---

# More supported models can be referenced here: https://ai.google.dev/gemini-api/docs/models#model-variations
MODEL_GEMINI_2_0_FLASH = "gemini-2.0-flash"

# More supported models can be referenced here: https://docs.litellm.ai/docs/providers/openai#openai-chat-completion-models
MODEL_GPT_4O = "openai/gpt-4.1" # You can also try: gpt-4.1-mini, gpt-4o etc.

# More supported models can be referenced here: https://docs.litellm.ai/docs/providers/anthropic
MODEL_CLAUDE_SONNET = "anthropic/claude-sonnet-4-20250514" # You can also try: claude-opus-4-20250514 , claude-3-7-sonnet-20250219 etc

print("\nEnvironment configured.")


# Define tools and agents

def priority_solver(tasks: list) -> list:
    """Calculates priority using the WSJF algorithm (Value/Effort)."""
    # Logic to rank tasks based on weight and estimated hours
    ranked_tasks = sorted(tasks, key=lambda x: x['weight']/x['effort'], reverse=True)
    return ranked_tasks

def conflict_detector(proposed_slots: list, timetable: list) -> bool:
    """Checks if a proposed study block overlaps with a fixed lecture."""
    # Returns True if a conflict exists
    pass


# Define specialized agents
scheduler = LlmAgent(
    name = 'scheduler',
    description="Maximize time efficiency"
)

welfare = LlmAgent(
    name = "welfare",
    description = "Ensure 8 hours sleep and mental breaks..."

)
academic = LlmAgent(
    name = "academic",
    description = "Prioritize tasks with >20% grade weight..."
)

# Define the debate room
debate_room = ParallelAgent(
    name = "debate_room",
    sub_agents = [scheduler, welfare, academic]
)

# Define judge agent
judge = LlmAgent(
    name = "scoringAgent",
    instruction="""Analyze the 3 proposals in 'debate_proposals'.
    Do not seek consensus. Score each rationale based on its alignment
    with the student's long-term success. Select the highest score."""
)

mas_ias = SequentialAgent(
    name = 'MAS_IAS_orchestrator',
    sub_agents = [debate_room, judge]
)
